id: P004256
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:05:14.127332
source_metadata:
  id: bdr:W23663
  title: གཅུང་པོ་དོན་ཡོད་དོན་གྲུབ་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    6f7303bba71c4b129e7cee005ad8a846:
      image_group_id: I1KG22779
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
