id: P004256
initial_creation_type: ocr
source_metadata:
  id: bdr:W23663
  title: གཅུང་པོ་དོན་ཡོད་དོན་གྲུབ་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    6f7303bba71c4b129e7cee005ad8a846:
      image_group_id: I1KG22779
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
